apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main
  namespace: monitoring
  labels:
    app: alertmanager
    release: prometheus
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'alertmanager@example.com'
      smtp_auth_password: 'your-password'
      smtp_require_tls: true
    route:
      receiver: 'email-config'
    receivers:
    - name: 'email-config'
      email_configs:
      - to: 'abdoul-aziz.zakari-madougou@intervenants.efrei.net'
        send_resolved: true
