apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-not-running-alert
  namespace: default
spec:
  groups:
  - name: kubernetes-alerts
    rules:
    - alert: PodNotRunning
      expr: kube_pod_status_phase{phase="Failed"} == 1
      for: 5m
      labels:
        severity: critical
      annotations:
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in Failed state for more than 5 minutes."
        summary: "Pod is in Failed state."

