apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    alertmanager: main
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'rnvscathalina22@gmail.com'
      smtp_auth_username: 'rnvscathalina22@gmail.com'
      smtp_auth_password: 'Mailpassword'
      smtp_require_tls: true
    route:
      receiver: 'email-notifications'
    receivers:
      - name: 'email-notifications'
        email_configs:
          - to: 'abdoul-aziz.zakari-madougou@intervenants.efrei.net'
            send_resolved: true
            subject: '[ALERT] Pod Not Running'
            text: 'Alert: Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in Failed state for more than 5 minutes.'

      - to: 'abdoul-aziz.zakari-madougou@intervenants.efrei.net'
        send_resolved: true
