apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-app
  template:
    metadata:
      labels:
        app: my-go-app
    spec:
      containers:
        - name: my-go-app
          image: my-go-app
          imagePullPolicy: Never  # Doit être ici, dans la section du conteneur
          ports:
            - containerPort: 8081
